huh_encore:
    js_entries:
        - { name: contao-linkchecker-bundle, file: 'vendor/heimrichhannot/contao-linkchecker-bundle/src/Resources/public/js/contao-linkchecker-bundle.es6.js' }
    unset_global_keys:
        js:
            - linkchecker