services:
  huh.linkchecker.manager.linkchecker:
    class: HeimrichHannot\LinkCheckerBundle\Manager\LinkChecker
    public: true
    autowire: true
  HeimrichHannot\LinkCheckerBundle\Manager\LinkChecker: '@huh.linkchecker.manager.linkchecker'



  HeimrichHannot\LinkCheckerBundle\:
    resource: '../../{Asset,EventListener}/*'
    autowire: true
    autoconfigure: true