services:
  huh.linkchecker.manager.linkchecker:
    class: HeimrichHannot\LinkCheckerBundle\Manager\LinkChecker
    public: true
  HeimrichHannot\LinkCheckerBundle\Widget\LinkChecker: '@huh.linkchecker.manager.linkchecker'

  HeimrichHannot\LinkCheckerBundle\EventListener\ExecutePreActionsListener:
    autowire: true
    public: true